import type { GraphPayload } from '@agnetos/contracts';

/** A tiny stored payload for tests. Counts are real for *this* fixture, not a demo of 150. */
export const GRAPH_FIXTURE: GraphPayload = {
  version: 'sha256:test-map',
  computedAt: '2026-08-15T00:00:00.000Z',
  bounds: { x: [-400, 400], y: [-400, 400] },
  core: { x: 0, y: 0, brainCompleteness: 0 },
  departments: [
    {
      id: 'sales',
      label: 'Sales',
      angle: -Math.PI / 2,
      sublabels: ['lead sourcing', 'enrichment', ''],
      anchor: 'sales/_anchor',
      liveCount: 1,
      totalCount: 1,
    },
    {
      id: 'deals',
      label: 'Deals',
      angle: -Math.PI / 2 + (2 * Math.PI) / 7,
      sublabels: ['', '', ''],
      anchor: 'deals/_anchor',
      liveCount: 0,
      totalCount: 0,
    },
  ],
  nodes: [
    {
      id: 'sales/_anchor',
      kind: 'anchor',
      label: 'Sales',
      department: 'sales',
      cluster: null,
      icon: null,
      status: 'draft',
      scheduled: false,
      approvalPending: false,
      depth: 1,
      x: 0,
      y: -220,
      r: 22,
    },
    {
      id: 'sales/account-enrichment',
      kind: 'job',
      label: 'Account Enrichment',
      department: 'sales',
      cluster: 'enrichment',
      icon: null,
      status: 'live',
      scheduled: false,
      approvalPending: false,
      depth: 2,
      x: 12,
      y: -320,
      r: 16,
    },
    {
      id: 'deals/_anchor',
      kind: 'anchor',
      label: 'Deals',
      department: 'deals',
      cluster: null,
      icon: null,
      status: 'draft',
      scheduled: false,
      approvalPending: false,
      depth: 1,
      x: 180,
      y: -80,
      r: 22,
    },
  ],
  edges: [
    { source: 'core', target: 'sales/_anchor', kind: 'tree', curve: 0.12, pulse: true },
    {
      source: 'sales/_anchor',
      target: 'sales/account-enrichment',
      kind: 'tree',
      curve: -0.1,
      pulse: true,
    },
    { source: 'core', target: 'deals/_anchor', kind: 'tree', curve: 0.14, pulse: false },
  ],
};
