/**
 * Langfuse trace sink (§3.5).
 *
 * Self-hosted Langfuse ≥ 3.22 exposes an OTLP/HTTP endpoint at
 * `POST {baseUrl}/api/public/otel/v1/traces` with HTTP Basic auth
 * (`base64(publicKey:secretKey)`). We speak OTLP/JSON to it with `fetch` — no SDK,
 * no dependency, and no chance of a transitive package deciding to phone home. The
 * legacy `/api/public/ingestion` endpoint is deprecated in Langfuse v4, which is why
 * this is OTLP rather than the batch-event API.
 *
 * PDPL (Part VII.4): `baseUrl` must resolve on the tailnet. `assertLocalSink` refuses
 * to start against a hosted Langfuse Cloud region — the constraint is "traces stay on
 * our box", and a config typo is exactly how that constraint gets broken quietly.
 *
 * Failure policy: shipping a trace is best-effort. A Langfuse outage must never fail a
 * run or blank a dashboard, which is why every rendered number comes from the Postgres
 * ledger and Langfuse only holds the narrative.
 */

import type { TraceSink } from './types.ts';

export type LangfuseConfig = {
  /** Where traces are POSTed. Compose-internal (`http://langfuse:3000`) in the stack. */
  baseUrl: string;
  /**
   * Where a **human's browser** reaches Langfuse. Distinct from `baseUrl` on purpose:
   * `langfuse:3000` only resolves inside the compose network, so a link built from it is
   * dead in the drawer even though the trace behind it landed correctly.
   *
   * Falls back to `baseUrl` when unset, which is right for a single-origin deployment and
   * wrong-but-unchanged for compose — so infra sets `LANGFUSE_PUBLIC_URL` explicitly.
   */
  publicUrl?: string;
  publicKey: string;
  secretKey: string;
  projectId: string;
  /** Milliseconds before a trace POST is abandoned. */
  timeoutMs?: number;
};

/** Hosts that would take our clients' data out of the region. Refused on sight. */
const FORBIDDEN_HOSTS = [
  'cloud.langfuse.com',
  'us.cloud.langfuse.com',
  'eu.cloud.langfuse.com',
  'hipaa.cloud.langfuse.com',
];

export function assertLocalSink(baseUrl: string): void {
  let host: string;
  try {
    host = new URL(baseUrl).hostname.toLowerCase();
  } catch {
    throw new Error(`LANGFUSE_BASE_URL is not a URL: ${baseUrl}`);
  }
  if (FORBIDDEN_HOSTS.includes(host)) {
    throw new Error(
      `Refusing to send traces to ${host}. Part VII.4: traces stay on our box — ` +
        'no US/EU SaaS trace sinks. Point LANGFUSE_BASE_URL at the tailnet service.',
    );
  }
}

/** 32 hex chars — a W3C trace id. Generated by us so the trace URL exists before the run does. */
export function newTraceId(): string {
  return randomHex(16);
}

/** 16 hex chars — a W3C span id. */
export function newSpanId(): string {
  return randomHex(8);
}

function randomHex(bytes: number): string {
  const buf = new Uint8Array(bytes);
  globalThis.crypto.getRandomValues(buf);
  let out = '';
  for (const b of buf) out += b.toString(16).padStart(2, '0');
  return out;
}

/** OTLP wants nanoseconds since epoch, as a decimal string. */
export function toUnixNano(date: Date): string {
  return `${BigInt(date.getTime()) * 1_000_000n}`;
}

export type AttrValue = string | number | boolean | undefined | null;

/**
 * The three ids **every** span in this system carries, and the reason they are a type
 * rather than a convention.
 *
 * PDPL rule 4 (*client data does not cross clients*) was enforceable in Postgres, in the
 * library plane and in the brain, and merely *stateable* here: `instrument.ts` wrote
 * agent, department, trigger, status, dry_run, cost_source and redactions onto the root
 * span and no project, so N clients' traces landed in one Langfuse project, interleaved,
 * with no attribute to filter on. Rule 7 (right to erasure) is the harder half — a
 * deletion request has to be answerable by *selecting* a subject's data, and a trace
 * store with no client axis offers nothing to select by.
 *
 * The fix is structural on purpose. Making this a required member of `OtelSpan`
 * means a span that cannot name its project **does not compile** — the same shape
 * `lib/graph.ts` and `lib/panels.ts` took when they stopped importing `RunnerConfig`
 * so that reaching for the coordinator's path became a type error rather than a habit.
 * A span added next year gets the project because the compiler names the site, not
 * because whoever added it remembered this paragraph.
 *
 * All three are ids: a uuid and two slug paths (`{project}/{department}/{slug}`,
 * `{layer}:{path}@sha256:…`). None can carry client content, so none needs redacting.
 */
export type SpanScope = {
  'agnetos.run.id': string;
  'agnetos.project.id': string;
  'agnetos.agent.ref': string;
  /**
   * The thread this run belongs to (`Plan §12`, ADR-023) — **optional, and that is the
   * decision rather than the leftover.**
   *
   * The three fields above are required because none of them has a truthful absent state.
   * A run with no project is a run whose data cannot be filed; a run with no `agent.ref`
   * cannot say which agent it *was*. There is no value they could fall back to that is not
   * a guess about whose data this is, so the compiler refusing the call site is exactly
   * right.
   *
   * `thread_id` is different, and the difference is in the schema rather than in taste.
   * `ops.agent_runs.thread_id` ships **nullable on purpose** (`0008_threads.sql` §3): NULL
   * means *"this run predates threads"*, which is a true statement about a real run.
   *
   * **The anchor is the ledger's NOT NULL set, not `RunInit`'s required set, and that
   * choice is load-bearing rather than incidental.** The job of a required member here is
   * to make an *unfileable* datum a compile error, and a datum is unfileable exactly when
   * the plane it lands in cannot represent its absence. `project_id` is NOT NULL on
   * `ops.agent_runs`, so a run with no project cannot be recorded at all — required. A run
   * with no thread **can** be recorded, truthfully. Requiring it on the span while the
   * ledger tolerates NULL would have the trace plane assert something the ledger does not,
   * and when those two disagree the trace is the one that is lying: the ledger is what
   * every rendered number reads (`comms/specs/observability.md` decision 1), and the trace
   * only holds the narrative.
   *
   * That anchor is deliberately independent of whether `RunAttribution.threadId` is
   * required — a producer discipline on `runner-engineer`'s side of the seam, which moved
   * twice during M16 and settled optional for the same schema reason. Anchoring here to
   * *their* type would have made this member move with a decision that is not about spans;
   * anchoring to the migration means one fact moves one way, once, and takes both types
   * with it. Were this required while the column stayed nullable it would be a `NOT NULL`
   * whose only satisfying value is a placeholder — the M15 defect graded from the other
   * side (`contracts/thread-model.md` §5.3: *a NOT NULL nobody can satisfy and one that
   * holds are identical in a schema dump*).
   *
   * Optionality costs nothing at emit time: `attributes()` below drops `undefined`, so a
   * run with no thread emits **no** `agnetos.thread.id` attribute at all rather than an
   * empty string. "This run has no thread" and "this run's thread was not recorded" stay
   * the same absence, which is honest, because today they are the same fact.
   *
   * **The coupling is mechanical, not a promise.** `thread-scope-tracks-ledger.test.ts`
   * reads every migration: the day `ops.agent_runs.thread_id` becomes `NOT NULL`, that test
   * requires this member to lose its `?`. The required set of `SpanScope` tracks the
   * NOT NULL set of the ledger, and neither can move without the other going red.
   */
  'agnetos.thread.id'?: string;
};

/** Span attributes: anything you like, **plus** the scope, which is not optional. */
export type SpanAttributes = SpanScope & Record<string, AttrValue>;

function attributes(map: Record<string, AttrValue>): unknown[] {
  const out: unknown[] = [];
  for (const [key, value] of Object.entries(map)) {
    if (value === undefined || value === null) continue;
    if (typeof value === 'string') out.push({ key, value: { stringValue: value } });
    else if (typeof value === 'boolean') out.push({ key, value: { boolValue: value } });
    else if (Number.isInteger(value)) out.push({ key, value: { intValue: `${value}` } });
    else out.push({ key, value: { doubleValue: value } });
  }
  return out;
}

export type OtelSpan = {
  traceId: string;
  spanId: string;
  parentSpanId?: string;
  name: string;
  startTime: Date;
  endTime: Date;
  /** OTLP status: 1 = OK, 2 = ERROR. */
  error?: string;
  /** Scoped, always. See `SpanScope` — omitting the project is a compile error. */
  attributes: SpanAttributes;
};

/** Build the OTLP/JSON body for a set of spans that share a trace. */
export function buildOtlpPayload(spans: OtelSpan[], serviceName = 'agnetos-runner'): unknown {
  return {
    resourceSpans: [
      {
        resource: { attributes: attributes({ 'service.name': serviceName }) },
        scopeSpans: [
          {
            scope: { name: 'agnetos.observability', version: '1' },
            spans: spans.map((s) => ({
              traceId: s.traceId,
              spanId: s.spanId,
              parentSpanId: s.parentSpanId,
              name: s.name,
              kind: 1,
              startTimeUnixNano: toUnixNano(s.startTime),
              endTimeUnixNano: toUnixNano(s.endTime),
              attributes: attributes(s.attributes),
              status: s.error ? { code: 2, message: s.error } : { code: 1 },
            })),
          },
        ],
      },
    ],
  };
}

export function createLangfuseSink(config: LangfuseConfig): TraceSink {
  assertLocalSink(config.baseUrl);

  const endpoint = `${config.baseUrl.replace(/\/+$/, '')}/api/public/otel/v1/traces`;
  const auth = Buffer.from(`${config.publicKey}:${config.secretKey}`).toString('base64');
  const timeoutMs = config.timeoutMs ?? 5_000;

  return {
    async send(payload: unknown): Promise<void> {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), timeoutMs);
      try {
        const res = await fetch(endpoint, {
          method: 'POST',
          headers: { 'content-type': 'application/json', authorization: `Basic ${auth}` },
          body: JSON.stringify(payload),
          signal: controller.signal,
        });
        if (!res.ok) {
          // Body may echo the request; log the status only, never the response text.
          throw new Error(`Langfuse OTLP responded ${res.status}`);
        }
      } finally {
        clearTimeout(timer);
      }
    },

    /**
     * Built from `publicUrl`, not `baseUrl`. The two are the same string in a
     * single-origin deployment and different in compose, where the runner POSTs to
     * `http://langfuse:3000` and the human clicks `http://127.0.0.1:3001`. Using the send
     * host for the link produced a URL that was correct for the container and dead for
     * the person holding the phone.
     */
    urlFor(traceId: string): string {
      const origin = (config.publicUrl || config.baseUrl).replace(/\/+$/, '');
      return `${origin}/project/${config.projectId}/traces/${traceId}`;
    },
  };
}

/**
 * Sink used when Langfuse is not configured: runs still work, traces just aren't shipped.
 *
 * **`urlFor` returns `null`, and that is the whole point of this function.** It used to
 * default to `http://langfuse.tailnet:3000/project/local/traces/<id>` — a well-formed URL,
 * on a host that does not exist, for a project that was never created, pointing at a trace
 * that was never sent. That string was written into `ops.agent_runs.trace_url` and rendered
 * as a live link in LAST RUNS and the drawer.
 *
 * It is the same defect as reporting a 0/20 brain at 45%, `runs: 0` during a database
 * outage, and `tailscale: "online"` from a host with no Tailscale: **a configured value
 * reported as an observed one.** There is no trace, so there is no link. `null` is the
 * only honest answer, and every consumer already handles it — `traceUrl` is nullable in the
 * run store, the ledger column and the SSE `start`/`done` frames alike.
 */
export function createNullSink(): TraceSink {
  return {
    async send(): Promise<void> {
      /* traces disabled */
    },
    urlFor(): string | null {
      return null;
    },
  };
}

export function sinkFromEnv(env: Record<string, string | undefined> = process.env): TraceSink {
  // Compose pins `LANGFUSE_HOST` (infra owns compose). Accept either name so a
  // config typo does not silently drop traces onto the null sink.
  const baseUrl = env.LANGFUSE_BASE_URL ?? env.LANGFUSE_HOST;
  const publicKey = env.LANGFUSE_PUBLIC_KEY;
  const secretKey = env.LANGFUSE_SECRET_KEY;
  const projectId = env.LANGFUSE_PROJECT_ID ?? 'default';
  // Browser-facing origin for links, set by compose alongside the send host. Blank is
  // treated as unset so an empty `${LANGFUSE_PUBLIC_URL:-}` does not produce `/project/...`.
  const publicUrl = env.LANGFUSE_PUBLIC_URL?.trim() || undefined;
  if (!baseUrl || !publicKey || !secretKey) return createNullSink();
  return createLangfuseSink({ baseUrl, publicUrl, publicKey, secretKey, projectId });
}
