/**
 * Langfuse trace sink (§3.5).
 *
 * Self-hosted Langfuse ≥ 3.22 exposes an OTLP/HTTP endpoint at
 * `POST {baseUrl}/api/public/otel/v1/traces` with HTTP Basic auth
 * (`base64(publicKey:secretKey)`). We speak OTLP/JSON to it with `fetch` — no SDK,
 * no dependency, and no chance of a transitive package deciding to phone home. The
 * legacy `/api/public/ingestion` endpoint is deprecated in Langfuse v4, which is why
 * this is OTLP rather than the batch-event API.
 *
 * PDPL (Part VII.4): `baseUrl` must resolve on the tailnet. `assertLocalSink` refuses
 * to start against a hosted Langfuse Cloud region — the constraint is "traces stay on
 * our box", and a config typo is exactly how that constraint gets broken quietly.
 *
 * Failure policy: shipping a trace is best-effort. A Langfuse outage must never fail a
 * run or blank a dashboard, which is why every rendered number comes from the Postgres
 * ledger and Langfuse only holds the narrative.
 */

import type { TraceSink } from './types.ts';

export type LangfuseConfig = {
  baseUrl: string;
  publicKey: string;
  secretKey: string;
  projectId: string;
  /** Milliseconds before a trace POST is abandoned. */
  timeoutMs?: number;
};

/** Hosts that would take our clients' data out of the region. Refused on sight. */
const FORBIDDEN_HOSTS = [
  'cloud.langfuse.com',
  'us.cloud.langfuse.com',
  'eu.cloud.langfuse.com',
  'hipaa.cloud.langfuse.com',
];

export function assertLocalSink(baseUrl: string): void {
  let host: string;
  try {
    host = new URL(baseUrl).hostname.toLowerCase();
  } catch {
    throw new Error(`LANGFUSE_BASE_URL is not a URL: ${baseUrl}`);
  }
  if (FORBIDDEN_HOSTS.includes(host)) {
    throw new Error(
      `Refusing to send traces to ${host}. Part VII.4: traces stay on our box — ` +
        'no US/EU SaaS trace sinks. Point LANGFUSE_BASE_URL at the tailnet service.',
    );
  }
}

/** 32 hex chars — a W3C trace id. Generated by us so the trace URL exists before the run does. */
export function newTraceId(): string {
  return randomHex(16);
}

/** 16 hex chars — a W3C span id. */
export function newSpanId(): string {
  return randomHex(8);
}

function randomHex(bytes: number): string {
  const buf = new Uint8Array(bytes);
  globalThis.crypto.getRandomValues(buf);
  let out = '';
  for (const b of buf) out += b.toString(16).padStart(2, '0');
  return out;
}

/** OTLP wants nanoseconds since epoch, as a decimal string. */
export function toUnixNano(date: Date): string {
  return `${BigInt(date.getTime()) * 1_000_000n}`;
}

type AttrValue = string | number | boolean | undefined | null;

function attributes(map: Record<string, AttrValue>): unknown[] {
  const out: unknown[] = [];
  for (const [key, value] of Object.entries(map)) {
    if (value === undefined || value === null) continue;
    if (typeof value === 'string') out.push({ key, value: { stringValue: value } });
    else if (typeof value === 'boolean') out.push({ key, value: { boolValue: value } });
    else if (Number.isInteger(value)) out.push({ key, value: { intValue: `${value}` } });
    else out.push({ key, value: { doubleValue: value } });
  }
  return out;
}

export type OtelSpan = {
  traceId: string;
  spanId: string;
  parentSpanId?: string;
  name: string;
  startTime: Date;
  endTime: Date;
  /** OTLP status: 1 = OK, 2 = ERROR. */
  error?: string;
  attributes: Record<string, AttrValue>;
};

/** Build the OTLP/JSON body for a set of spans that share a trace. */
export function buildOtlpPayload(spans: OtelSpan[], serviceName = 'agnetos-runner'): unknown {
  return {
    resourceSpans: [
      {
        resource: { attributes: attributes({ 'service.name': serviceName }) },
        scopeSpans: [
          {
            scope: { name: 'agnetos.observability', version: '1' },
            spans: spans.map((s) => ({
              traceId: s.traceId,
              spanId: s.spanId,
              parentSpanId: s.parentSpanId,
              name: s.name,
              kind: 1,
              startTimeUnixNano: toUnixNano(s.startTime),
              endTimeUnixNano: toUnixNano(s.endTime),
              attributes: attributes(s.attributes),
              status: s.error ? { code: 2, message: s.error } : { code: 1 },
            })),
          },
        ],
      },
    ],
  };
}

export function createLangfuseSink(config: LangfuseConfig): TraceSink {
  assertLocalSink(config.baseUrl);

  const endpoint = `${config.baseUrl.replace(/\/+$/, '')}/api/public/otel/v1/traces`;
  const auth = Buffer.from(`${config.publicKey}:${config.secretKey}`).toString('base64');
  const timeoutMs = config.timeoutMs ?? 5_000;

  return {
    async send(payload: unknown): Promise<void> {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), timeoutMs);
      try {
        const res = await fetch(endpoint, {
          method: 'POST',
          headers: { 'content-type': 'application/json', authorization: `Basic ${auth}` },
          body: JSON.stringify(payload),
          signal: controller.signal,
        });
        if (!res.ok) {
          // Body may echo the request; log the status only, never the response text.
          throw new Error(`Langfuse OTLP responded ${res.status}`);
        }
      } finally {
        clearTimeout(timer);
      }
    },

    urlFor(traceId: string): string {
      return `${config.baseUrl.replace(/\/+$/, '')}/project/${config.projectId}/traces/${traceId}`;
    },
  };
}

/** Sink used when Langfuse is not configured: runs still work, traces just aren't shipped. */
export function createNullSink(baseUrl = 'http://langfuse.tailnet:3000', projectId = 'local'): TraceSink {
  return {
    async send(): Promise<void> {
      /* traces disabled */
    },
    urlFor(traceId: string): string {
      return `${baseUrl.replace(/\/+$/, '')}/project/${projectId}/traces/${traceId}`;
    },
  };
}

export function sinkFromEnv(env: Record<string, string | undefined> = process.env): TraceSink {
  // Compose pins `LANGFUSE_HOST` (infra owns compose). Accept either name so a
  // config typo does not silently drop traces onto the null sink.
  const baseUrl = env.LANGFUSE_BASE_URL ?? env.LANGFUSE_HOST;
  const publicKey = env.LANGFUSE_PUBLIC_KEY;
  const secretKey = env.LANGFUSE_SECRET_KEY;
  const projectId = env.LANGFUSE_PROJECT_ID ?? 'default';
  if (!baseUrl || !publicKey || !secretKey) return createNullSink();
  return createLangfuseSink({ baseUrl, publicKey, secretKey, projectId });
}
